In [1]:
import numpy as np

In [2]:
arr = np.array([1,3,5,4,5])

In [3]:
arr

array([1, 3, 5, 4, 5])

In [8]:
myarr = np.array([[1,4,3,4,343434,5]] , np.int64)

In [9]:
myarr[0,2]

np.int64(3)

In [10]:
myarr.shape

(1, 6)

In [11]:
# lets change element of any array

In [15]:
myarr[0,5] #type index

np.int64(45)

In [18]:
myarr[0,5] = 45 #give a value of index to change

In [19]:
myarr

array([[     1,      4,      3,      4, 343434,     45]])

In [20]:
# it change element on the fifth index

In [21]:
myarr.size

6

In [32]:
zerox = np.zeros((5,5))

In [33]:
zerox*2

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [34]:
zerox

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [35]:
zerox.dtype

dtype('float64')

In [36]:
# print number array using range 

In [37]:
rng = np.arange(15)

In [38]:
rng

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

In [39]:
rng2 = np.arange(15+1)

In [40]:
rng2

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15])

In [41]:
rng2.size

16

In [42]:
rng2.shape

(16,)

In [44]:
# now see how much number we want in two number

In [49]:
lspace = np.linspace(1,50,10)

In [50]:
lspace

array([ 1.        ,  6.44444444, 11.88888889, 17.33333333, 22.77777778,
       28.22222222, 33.66666667, 39.11111111, 44.55555556, 50.        ])

In [51]:
#  for random value

In [56]:
emp = np.empty((6,6), np.int64) # i use int64 for claim all int value

In [58]:
emp

array([[23925768161198147, 32370111954616435, 31525674139713628,
        18296268630261857, 27303364806049904, 21392493373358196],
       [30399714103066735, 31244212046397532, 30681189080760423,
        34058815785402483, 30962724186357876, 32651616994721884],
       [14355696265920616, 21392493370277937, 32370017465139305,
        12666807751278697, 30118247716159600, 32370056120172641],
       [27584981515894876, 34058953225076853, 28429479460143196,
        32088624092938350, 31525592535138405, 33214481050108025],
       [31525605419516004, 33214481050108025, 32932993188167780,
        28429436510797934, 28148017369448540, 26740552291975269],
       [27866499443196016, 26740616716288101, 26740621010337902,
        30681240620171363, 12948278432628833, 30962247446102128]])

In [59]:
# asis

In [60]:
x = [[1,2,3],[4,5,6],[7,0,1]]

In [61]:
arry = np.array(x)

In [62]:
arry

array([[1, 2, 3],
       [4, 5, 6],
       [7, 0, 1]])

In [63]:
sum(axis = 0)

TypeError: sum() takes at least 1 positional argument (0 given)

In [64]:
arry.sum(axis=0)

array([12,  7, 10])

In [65]:
arry.sum(axis=1)

array([ 6, 15,  8])

In [66]:
# transform

In [67]:
arry.T

array([[1, 4, 7],
       [2, 5, 0],
       [3, 6, 1]])

In [68]:
# get item

In [70]:
for item in arry.flat:
    print(item)

1
2
3
4
5
6
7
0
1


In [71]:
# ndim for check dimetion that array is 1d or 2d or more

In [72]:
arry.ndim

2

In [73]:
arry.nbytes

72

In [74]:
arry.size

9

In [75]:
# take index that where is you bigest element

In [76]:
one = np.array([1,2,4,4545,67,56])

In [78]:
one.argmax() #this is function beacouse it has () which has () are function and without () are attribute

np.int64(3)

In [80]:
one.argmin() # check which is minimum number in array

np.int64(0)

In [81]:
# get acending order index

In [82]:
one.argsort() 

array([0, 1, 2, 5, 4, 3])

In [84]:
# these same function in 2D array

In [85]:
arry

array([[1, 2, 3],
       [4, 5, 6],
       [7, 0, 1]])

In [86]:
arry.argmax()

np.int64(6)

In [88]:
arry.argmin()

np.int64(7)

In [89]:
arry.argsort()

array([[0, 1, 2],
       [0, 1, 2],
       [1, 2, 0]])

In [90]:
arry.argmax(axis=0)

array([2, 1, 1])

In [91]:
arry

array([[1, 2, 3],
       [4, 5, 6],
       [7, 0, 1]])

In [92]:
arry.argsort(axis=1)

array([[0, 1, 2],
       [0, 1, 2],
       [1, 2, 0]])

In [93]:
arry.argsort(axis=0)

array([[0, 2, 2],
       [1, 0, 0],
       [2, 1, 1]])

In [94]:
arry2 = np.array([[1,2,3],[4,5,6],[7,8,9]])

In [95]:
arry+arry2

array([[ 2,  4,  6],
       [ 8, 10, 12],
       [14,  8, 10]])

In [96]:
arry

array([[1, 2, 3],
       [4, 5, 6],
       [7, 0, 1]])

In [97]:
arry2.sum()

np.int64(45)

In [98]:
arry.sum()

np.int64(29)